/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 3.5 */
/* Thu Jul 04 17:23:43 2024 */

/* parameterized module instance */
add __ (.DataA( ), .DataB( ), .Cin( ), .Result( ), .Cout( ));
