/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.7 */
/* Wed Jun 19 08:29:16 2024 */

/* parameterized module instance */
PLL __ (.CLKI( ), .CLKOP( ));
