/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 7.5 */
/* Sun Jul 21 17:17:41 2024 */

/* parameterized module instance */
ram __ (.Clock( ), .ClockEn( ), .Reset( ), .WE( ), .Address( ), .Data( ), 
    .Q( ));
